package sistemalicencias.views;

import java.awt.Image;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import sistemalicencias.accesoDatos.EmpleadoData;
import sistemalicencias.entidades.Empleado;


public class ListaEmpleados extends javax.swing.JInternalFrame {
private int i = 0;
    /**
     * Creates new form ListaEmpleados
     */
    public ListaEmpleados() {
        initComponents();
        setearIcono(jLabel1, "src/Imagenes/uader.png");
        modelo();
        listarEmpleados();
        
    }

    private DefaultTableModel tabla = new DefaultTableModel() {

        public boolean isCellEditable(int row, int column) {

            return column != 2 && column != 4;
        }
    };
    
    private void modelo() {
        tabla.addColumn("Apellido");
        tabla.addColumn("Nombre");
        tabla.addColumn("Dni");
        tabla.addColumn("Teléfono");
        tabla.addColumn("Estado");

        jtTable.setModel(tabla);

        TableColumnModel columnModel = jtTable.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(80);
        columnModel.getColumn(1).setPreferredWidth(80);
        columnModel.getColumn(2).setPreferredWidth(80);
        columnModel.getColumn(3).setPreferredWidth(80);
        columnModel.getColumn(4).setPreferredWidth(50);
    }
    
    public void listarEmpleados() {
    EmpleadoData ed = new EmpleadoData();
    
    if (!jtDocumento.getText().isEmpty()) {
        tabla.setRowCount(0);
        for (Empleado empleado : ed.listarEmpleadoPorDni(jtDocumento.getText())) {
            tabla.addRow(new Object[]{empleado.getApellido(), empleado.getNombre(),
                    empleado.getDni(), empleado.getTelefono(), empleado.getEstado()});
        }
    } else {
        tabla.setRowCount(0);
        for (Empleado empleado : ed.listarEmpleadoPorDni(jtDocumento.getText())) {
            tabla.addRow(new Object[]{empleado.getApellido(), empleado.getNombre(), empleado.getDni(), empleado.getTelefono(), empleado.getEstado()});
        }
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jtDocumento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtTable);

        jLabel3.setText("Documento");

        jtDocumento.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jtDocumentoComponentAdded(evt);
            }
        });
        jtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDocumentoActionPerformed(evt);
            }
        });
        jtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtDocumentoKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Quitar baja o Dar de baja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Volver al menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("x");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(64, 64, 64)
                        .addComponent(jtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDocumentoActionPerformed
        // TODO add your handling code here:
        listarEmpleados();
    }//GEN-LAST:event_jtDocumentoActionPerformed

    private void jtDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDocumentoKeyReleased
        // TODO add your handling code here:
        if (!jtDocumento.getText().isEmpty()) {
            //jtTable.clearSelection();
            listarEmpleados();
        } else {
            listarEmpleados();
        }
    }//GEN-LAST:event_jtDocumentoKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EmpleadoData ed = new EmpleadoData();
        try{
            int filaSeleccionada = jtTable.getSelectedRow();
            int estado = (int) tabla.getValueAt(filaSeleccionada, 4);
            String dni = (String) tabla.getValueAt(filaSeleccionada, 2);
            
            if(jtTable.getSelectedRow() > -1){
                
            if(estado == 1){
                int x = JOptionPane.showConfirmDialog(this, "¿Dar de baja al empleado seleccionado?",
                "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                    if (x == 0) {
                        ed.cambiarEstado(0, dni);
                        jtDocumento.setText("");
                    }
                
            } else if(estado == 0){
                int x = JOptionPane.showConfirmDialog(this, "¿Quitar baja al empleado seleccionado?",
                "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                    if (x == 0) {
                        ed.cambiarEstado(1, dni);
                        jtDocumento.setText("");
                    }
                
            }
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un empleado", "Error", JOptionPane.WARNING_MESSAGE);
            }
       } catch(java.lang.ArrayIndexOutOfBoundsException error){
           JOptionPane.showMessageDialog(this, "Seleccione un empleado", "Error", JOptionPane.WARNING_MESSAGE);
       }
       
       listarEmpleados();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
        EmpleadoData ed = new EmpleadoData();
        Empleado emp = new Empleado();
        String dni = jtDocumento.getText();
        emp = ed.buscarEmpleadoUnico(dni);

        int filaSeleccionada = jtTable.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un empleado", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        emp.setApellido(tabla.getValueAt(filaSeleccionada, 0).toString());
        emp.setNombre(tabla.getValueAt(filaSeleccionada, 1).toString());
        emp.setTelefono(tabla.getValueAt(filaSeleccionada, 3).toString());

        ed.modificarEmpleado(emp, dni);
        int todoCorrecto = 1;
        
        if(todoCorrecto == 1){
            i = 0;
        }

    }  catch (java.lang.ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(this, "Seleccione un empleado", "Error", JOptionPane.WARNING_MESSAGE);
    }
        
       
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTableMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtTableMousePressed

    private void jtTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTableMouseClicked
        // TODO add your handling code here:
        
            
            if(i == 0){
                //if(jtTable.getSelectedRow() != -1){
                    int filaSeleccionada = jtTable.getSelectedRow();
                    String dni = (String) tabla.getValueAt(filaSeleccionada, 2);
                    jtDocumento.setText(dni);
                    listarEmpleados();
                    jtTable.selectAll();
                //}
                i=1;
                System.out.println(i);
            }
            
        
        //
        //jtTable.selectAll();
        
       
    }//GEN-LAST:event_jtTableMouseClicked

    private void jtDocumentoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jtDocumentoComponentAdded
        // TODO add your handling code here:
        //listarEmpleados();
    }//GEN-LAST:event_jtDocumentoComponentAdded

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jtDocumento.setText("");
        listarEmpleados();
        i=0;
    }//GEN-LAST:event_jButton4ActionPerformed
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtDocumento;
    private javax.swing.JTable jtTable;
    // End of variables declaration//GEN-END:variables

    private void setearIcono(JLabel jLabelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(300, 100, Image.SCALE_DEFAULT));
        jLabelName.setIcon(icon);
        this.repaint();
    }
    
    public void borrado() {
        jtDocumento.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                listarEmpleados();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }

        });


    }

}
